name: Release docs

on:
  schedule:
    # Triggers the workflow every day at 17:30 UTC
    - cron:  '30 17 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        dotnet: [5.0.400]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore projects
      run: dotnet restore FSharp.Core\FSharp.Core.fsproj
    - name: Checkout fsharp master
      run: git clone https://github.com/dotnet/fsharp --depth 1 fsharp -b main
    - name: Build fsharp master (turn of CI build status)
      run: cd fsharp && eng\CIBuild.cmd
    - name: Checkout FSharp.Formatting master
      run: git clone https://github.com/fsprojects/FSharp.Formatting --depth 1 FSharp.Formatting 
    - name: Build FSharp.Formatting master
      run: cd FSharp.Formatting && .\build -t Build
    - name: Run fsdocs
      run: dotnet FSharp.Formatting\src\FSharp.Formatting.CommandTool\bin\Release\net5.0\fsdocs.dll build --sourcefolder fsharp
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
